using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._OE14.UserInterface.Systems.Skill.Window;

[GenerateTypedNameReferences]
public sealed partial class OE14SkillWindow : DefaultWindow
{
    public OE14SkillWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
