- type: entity
  parent:
  - OE14ClothingCloakBase
  id: OE14ClothingCloakGuildmasterCape
  name: guildmaster cape
  description: The colors green and gold tell you that you're looking at a higher
    power.
  components:
  - type: Sprite
    sprite: _OE14/Clothing/Cloak/Roles/Mercenary/guildmaster_cape.rsi
  - type: Clothing
    sprite: _OE14/Clothing/Cloak/Roles/Mercenary/guildmaster_cape.rsi
  localizationId: ent-OE14ClothingCloakGuildmasterCape
