using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : DefaultWindow
{
    // Properties are auto-generated from XAML with Access="Public"
    // StrengthValue, VitalityValue, DexterityValue, IntelligenceValue
    // StrengthBar, VitalityBar, DexterityBar, IntelligenceBar
    // StatsPanel

    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
