using System.IO;
using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Shared._OE14.CharacterStats.Components;
using Content.Shared._OE14.Skill.Components;
using Content.Shared._OE14.Skill.Prototypes;
using Content.Client.Lobby.UI.Loadouts;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.CCVar;
using Content.Shared.Clothing;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;
        private bool _allowFlavorText;

        private FlavorText.FlavorText? _flavorText;
        private TextEdit? _flavorTextEdit;

        // One at a time.
        private LoadoutWindow? _loadoutWindow;

        private bool _exporting;
        private bool _imaging;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// Entity used for the profile editor preview
        /// </summary>
        public EntityUid PreviewDummy;

        /// <summary>
        /// Temporary override of their selected job, used to preview roles.
        /// </summary>
        public JobPrototype? JobOverride;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private List<SpeciesPrototype> _species = new();

        private List<(string, RequirementsSelector)> _jobPriorities = new();

        private readonly Dictionary<string, BoxContainer> _jobCategories;

        // OE14 Stats bars and colors
        private Action<float>? _strBarSetter;
        private Action<float>? _vitBarSetter;
        private Action<float>? _dexBarSetter;
        private Action<float>? _intBarSetter;

        private static readonly Color StrColor  = Color.FromHex("#d4a84b");
        private static readonly Color VitColor  = Color.FromHex("#e05050");
        private static readonly Color DexColor  = Color.FromHex("#50c878");
        private static readonly Color IntColor  = Color.FromHex("#5090e0");

        private Direction _previewRotation = Direction.North;

        private ColorSelectorSliders _rgbSkinColorSelector;

        private bool _isDirty;

        private static readonly ProtoId<GuideEntryPrototype> DefaultSpeciesGuidebook = "Species";

        public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

        private ISawmill _sawmill;

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?) _preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex) args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int) Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int) Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int) Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int) Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender) args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                UpdateHairPickers();
                OnSkinColorOnValueChanged();
            };

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region Hair

            HairStylePicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(newStyle.id));
                ReloadPreview();
            };

            HairStylePicker.OnColorChanged += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairColor(newColor.marking.MarkingColors[0]));
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnMarkingSelect += newStyle =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(newStyle.id));
                ReloadPreview();
            };

            FacialHairPicker.OnColorChanged += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairColor(newColor.marking.MarkingColors[0]));
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            HairStylePicker.OnSlotRemove += _ =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(HairStyles.DefaultHairStyle)
                );
                UpdateHairPickers();
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotRemove += _ =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(HairStyles.DefaultFacialHairStyle)
                );
                UpdateHairPickers();
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            HairStylePicker.OnSlotAdd += delegate()
            {
                if (Profile is null)
                    return;

                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.Hair, Profile.Species).Keys
                    .FirstOrDefault();

                if (string.IsNullOrEmpty(hair))
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithHairStyleName(hair)
                );

                UpdateHairPickers();
                UpdateCMarkingsHair();
                ReloadPreview();
            };

            FacialHairPicker.OnSlotAdd += delegate()
            {
                if (Profile is null)
                    return;

                var hair = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.FacialHair, Profile.Species).Keys
                    .FirstOrDefault();

                if (string.IsNullOrEmpty(hair))
                    return;

                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithFacialHairStyleName(hair)
                );

                UpdateHairPickers();
                UpdateCMarkingsFacialHair();
                ReloadPreview();
            };

            #endregion Hair

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int) value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference) args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                Markings.CurrentEyeColor = Profile.Appearance.EyeColor;
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-jobs-tab"));

            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int) PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int) PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode) args.Id);
                SetDirty();
            };

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs

            TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-antags-tab"));

            RefreshTraits();

            #region OE14 Stats

            TabContainer.SetTabTitle(4, Loc.GetString("oe14-tab-stats"));

            OE14StrPlus.OnPressed += _ => OE14SpendStatPoint("strength", +1);
            OE14StrMinus.OnPressed += _ => OE14SpendStatPoint("strength", -1);
            OE14VitPlus.OnPressed += _ => OE14SpendStatPoint("vitality", +1);
            OE14VitMinus.OnPressed += _ => OE14SpendStatPoint("vitality", -1);
            OE14DexPlus.OnPressed += _ => OE14SpendStatPoint("dexterity", +1);
            OE14DexMinus.OnPressed += _ => OE14SpendStatPoint("dexterity", -1);
            OE14IntPlus.OnPressed += _ => OE14SpendStatPoint("intelligence", +1);
            OE14IntMinus.OnPressed += _ => OE14SpendStatPoint("intelligence", -1);

            // Build dual-color bars
            OE14BuildStatBar(OE14StrBarSlot, StrColor, out _strBarSetter);
            OE14BuildStatBar(OE14VitBarSlot, VitColor, out _vitBarSetter);
            OE14BuildStatBar(OE14DexBarSlot, DexColor, out _dexBarSetter);
            OE14BuildStatBar(OE14IntBarSlot, IntColor, out _intBarSetter);

            #endregion OE14 Stats

            #region Markings

            TabContainer.SetTabTitle(5, Loc.GetString("humanoid-profile-editor-markings-tab"));

            Markings.OnMarkingAdded += OnMarkingChange;
            Markings.OnMarkingRemoved += OnMarkingChange;
            Markings.OnMarkingColorChange += OnMarkingChange;
            Markings.OnMarkingRankChange += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            IsDirty = false;
        }

        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        public void RefreshFlavorText()
        {
            if (_allowFlavorText)
            {
                if (_flavorText != null)
                    return;

                _flavorText = new FlavorText.FlavorText();
                TabContainer.AddChild(_flavorText);
                TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));
                _flavorTextEdit = _flavorText.CFlavorTextInput;

                _flavorText.OnFlavorTextChanged += OnFlavorTextChange;
            }
            else
            {
                if (_flavorText == null)
                    return;

                TabContainer.RemoveChild(_flavorText);
                _flavorText.OnFlavorTextChanged -= OnFlavorTextChange;
                _flavorText.Dispose();
                _flavorTextEdit?.Dispose();
                _flavorTextEdit = null;
                _flavorText = null;
            }
        }

        /// <summary>
        /// Refreshes traits selector
        /// </summary>
        public void RefreshTraits()
        {
            TraitsList.DisposeAllChildren();

            var traits = _prototypeManager.EnumeratePrototypes<TraitPrototype>().OrderBy(t => Loc.GetString(t.Name)).ToList();
            TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-traits-tab"));

            if (traits.Count < 1)
            {
                TraitsList.AddChild(new Label
                {
                    Text = Loc.GetString("humanoid-profile-editor-no-traits"),
                    FontColorOverride = Color.Gray,
                });
                return;
            }

            // Setup model
            Dictionary<string, List<string>> traitGroups = new();
            List<string> defaultTraits = new();
            traitGroups.Add(TraitCategoryPrototype.Default, defaultTraits);

            foreach (var trait in traits)
            {
                if (trait.Category == null)
                {
                    defaultTraits.Add(trait.ID);
                    continue;
                }

                if (!_prototypeManager.HasIndex(trait.Category))
                    continue;

                var group = traitGroups.GetOrNew(trait.Category);
                group.Add(trait.ID);
            }

            // Create UI view from model
            foreach (var (categoryId, categoryTraits) in traitGroups)
            {
                TraitCategoryPrototype? category = null;

                if (categoryId != TraitCategoryPrototype.Default)
                {
                    category = _prototypeManager.Index<TraitCategoryPrototype>(categoryId);
                    // Label
                    TraitsList.AddChild(new Label
                    {
                        Text = Loc.GetString(category.Name),
                        Margin = new Thickness(0, 10, 0, 0),
                        StyleClasses = { StyleBase.StyleClassLabelHeading },
                    });
                }

                List<TraitPreferenceSelector?> selectors = new();
                var selectionCount = 0;

                foreach (var traitProto in categoryTraits)
                {
                    var trait = _prototypeManager.Index<TraitPrototype>(traitProto);
                    var selector = new TraitPreferenceSelector(trait);

                    selector.Preference = Profile?.TraitPreferences.Contains(trait.ID) == true;
                    if (selector.Preference)
                        selectionCount += trait.Cost;

                    selector.PreferenceChanged += preference =>
                    {
                        if (preference)
                        {
                            Profile = Profile?.WithTraitPreference(trait.ID, _prototypeManager);
                        }
                        else
                        {
                            Profile = Profile?.WithoutTraitPreference(trait.ID, _prototypeManager);
                        }

                        SetDirty();
                        RefreshTraits(); // If too many traits are selected, they will be reset to the real value.
                    };
                    selectors.Add(selector);
                }

                // Selection counter
                if (category is { MaxTraitPoints: >= 0 })
                {
                    TraitsList.AddChild(new Label
                    {
                        Text = Loc.GetString("humanoid-profile-editor-trait-count-hint", ("current", selectionCount) ,("max", category.MaxTraitPoints)),
                        FontColorOverride = Color.Gray
                    });
                }

                foreach (var selector in selectors)
                {
                    if (selector == null)
                        continue;

                    if (category is { MaxTraitPoints: >= 0 } &&
                        selector.Cost + selectionCount > category.MaxTraitPoints)
                    {
                        selector.Checkbox.Label.FontColorOverride = Color.Red;
                    }

                    TraitsList.AddChild(selector);
                }
            }
        }

        // OE14: Total stat points available at character creation.
        private const int OE14MaxStatValue = 10;
        private const int OE14CreationPointsDefault = 3;
        private const int OE14CreationPointsHuman = 5;

        /// <summary>
        /// Reads the base stats for the current species from its entity prototype.
        /// Returns neutral (5,5,5,5) if not found.
        /// </summary>
        private (int str, int vit, int dex, int intel) OE14GetBaseStats()
        {
            if (Profile == null)
                return (5, 5, 5, 5);

            if (!_prototypeManager.TryIndex<SpeciesPrototype>(Profile.Species, out var specProto))
                return (5, 5, 5, 5);

            if (!_prototypeManager.TryIndex<EntityPrototype>(specProto.Prototype, out var entProto))
                return (5, 5, 5, 5);

            if (!entProto.TryGetComponent<OE14CharacterStatsComponent>(out var baseStats, _entManager.ComponentFactory))
                return (5, 5, 5, 5);

            return (baseStats.Strength, baseStats.Vitality, baseStats.Dexterity, baseStats.Intelligence);
        }

        /// <summary>
        /// Returns the number of creation points available based on species.
        /// Humans get 5, all others get 3.
        /// </summary>
        private int OE14GetCreationPoints()
        {
            if (Profile == null)
                return OE14CreationPointsDefault;

            return Profile.Species == "OE14Human"
                ? OE14CreationPointsHuman
                : OE14CreationPointsDefault;
        }

        /// <summary>
        /// Refreshes the OE14 stat distribution UI from the current profile.
        /// </summary>
        public void RefreshOE14Stats()
        {
            if (Profile == null)
                return;

            var (baseStr, baseVit, baseDex, baseInt) = OE14GetBaseStats();

            var bonusStr = Profile.OE14StatBonusStrength;
            var bonusVit = Profile.OE14StatBonusVitality;
            var bonusDex = Profile.OE14StatBonusDexterity;
            var bonusInt = Profile.OE14StatBonusIntelligence;

            // Get spell bonuses from free learned skills
            var spellBonusStr = OE14GetSpellBonusForStat("strength");
            var spellBonusVit = OE14GetSpellBonusForStat("vitality");
            var spellBonusDex = OE14GetSpellBonusForStat("dexterity");
            var spellBonusInt = OE14GetSpellBonusForStat("intelligence");

            // Final stats include base + spend bonus + spell bonus
            var finalStr = Math.Min(baseStr + bonusStr + spellBonusStr, OE14MaxStatValue);
            var finalVit = Math.Min(baseVit + bonusVit + spellBonusVit, OE14MaxStatValue);
            var finalDex = Math.Min(baseDex + bonusDex + spellBonusDex, OE14MaxStatValue);
            var finalInt = Math.Min(baseInt + bonusInt + spellBonusInt, OE14MaxStatValue);

            var spent = bonusStr + bonusVit + bonusDex + bonusInt;
            var creationPoints = OE14GetCreationPoints();
            var available = creationPoints - spent;

            OE14AvailablePointsLabel.Text = Loc.GetString("oe14-stats-tab-points-value", ("value", available));

            // Base stats labels
            OE14StrengthBaseLabel.Text = baseStr.ToString();
            OE14VitalityBaseLabel.Text = baseVit.ToString();
            OE14DexterityBaseLabel.Text = baseDex.ToString();
            OE14IntelligenceBaseLabel.Text = baseInt.ToString();

            // Current (final) stats labels
            OE14StrengthValue.Text = finalStr.ToString();
            OE14VitalityValue.Text = finalVit.ToString();
            OE14DexterityValue.Text = finalDex.ToString();
            OE14IntelligenceValue.Text = finalInt.ToString();

            // Update bar fills (ratio 0-1 over MaxStatValue)
            var max = (float)OE14MaxStatValue;
            _strBarSetter?.Invoke(finalStr / max);
            _vitBarSetter?.Invoke(finalVit / max);
            _dexBarSetter?.Invoke(finalDex / max);
            _intBarSetter?.Invoke(finalInt / max);

            // Populate modifier containers (Spend mods + Spell mods from free skills)
            OE14PopulateModifierContainer(OE14StrengthModContainer, bonusStr, spellBonusStr);
            OE14PopulateModifierContainer(OE14VitalityModContainer, bonusVit, spellBonusVit);
            OE14PopulateModifierContainer(OE14DexterityModContainer, bonusDex, spellBonusDex);
            OE14PopulateModifierContainer(OE14IntelligenceModContainer, bonusInt, spellBonusInt);

            // + buttons: disabled if no budget left OR stat already at max (including spell bonuses)
            OE14StrPlus.Disabled = available <= 0 || (baseStr + bonusStr + spellBonusStr) >= OE14MaxStatValue;
            OE14VitPlus.Disabled = available <= 0 || (baseVit + bonusVit + spellBonusVit) >= OE14MaxStatValue;
            OE14DexPlus.Disabled = available <= 0 || (baseDex + bonusDex + spellBonusDex) >= OE14MaxStatValue;
            OE14IntPlus.Disabled = available <= 0 || (baseInt + bonusInt + spellBonusInt) >= OE14MaxStatValue;

            // - buttons: disabled if bonus is 0
            OE14StrMinus.Disabled = bonusStr <= 0;
            OE14VitMinus.Disabled = bonusVit <= 0;
            OE14DexMinus.Disabled = bonusDex <= 0;
            OE14IntMinus.Disabled = bonusInt <= 0;

            // Derived values preview
            var healthBonus = (finalVit - 5) * 12.5f;
            var critHp = 100f + healthBonus;
            var deadHp = critHp * 2f;
            var stamina = 100f * (1f + (finalDex - 5) * 0.1875f);
            var mana = 100f + (finalInt - 5) * 25f;
            var damage = finalStr >= 5
                ? 1f + (finalStr - 5) * 0.10f
                : 1f + (finalStr - 5) * 0.125f;

            var maxMana = Math.Max(0f, mana);
            var regenPerTick = maxMana / 100f;
            var staminaSlow = stamina * 0.25f;
            var staminaKnockdown = stamina;

            OE14DerivedHP.Text = critHp.ToString("0");
            OE14DerivedHPThresholds.Text = $"- {Math.Abs((int)critHp)} crit / - {Math.Abs((int)deadHp)} dead";

            OE14DerivedStamina.Text = $"{stamina:0} / {stamina:0}";
            OE14DerivedStaminaSlow.Text = $"slow at - {staminaSlow:0} / Knockdown at - {staminaKnockdown:0}";

            OE14DerivedMana.Text = maxMana.ToString("0");
            OE14DerivedManaRegen.Text = regenPerTick.ToString("0.##") + "/3s";

            OE14DerivedDamage.Text = damage.ToString("0.00") + "x";
        }

        private void OE14SpendStatPoint(string stat, int delta)
        {
            if (Profile == null)
                return;

            var (baseStr, baseVit, baseDex, baseInt) = OE14GetBaseStats();

            var bonusStr = Profile.OE14StatBonusStrength;
            var bonusVit = Profile.OE14StatBonusVitality;
            var bonusDex = Profile.OE14StatBonusDexterity;
            var bonusInt = Profile.OE14StatBonusIntelligence;
            var spent = bonusStr + bonusVit + bonusDex + bonusInt;
            var creationPoints = OE14GetCreationPoints();
            var available = creationPoints - spent;

            var (currentBonus, baseVal) = stat switch
            {
                "strength" => (bonusStr, baseStr),
                "vitality" => (bonusVit, baseVit),
                "dexterity" => (bonusDex, baseDex),
                "intelligence" => (bonusInt, baseInt),
                _ => (0, 5)
            };

            if (delta > 0 && available <= 0)
                return;
            if (delta > 0 && baseVal + currentBonus >= OE14MaxStatValue)
                return;
            if (delta < 0 && currentBonus <= 0)
                return;

            Profile = Profile.WithOE14StatBonus(stat, currentBonus + delta);
            SetDirty();
            RefreshOE14Stats();
        }

        /// <summary>
        /// Refreshes the species selector.
        /// </summary>
        public void RefreshSpecies()
        {
            SpeciesButton.Clear();
            _species.Clear();

            _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
            var speciesIds = _species.Select(o => o.ID).ToList();

            for (var i = 0; i < _species.Count; i++)
            {
                var name = Loc.GetString(_species[i].Name);
                SpeciesButton.AddItem(name, i);

                if (Profile?.Species.Equals(_species[i].ID) == true)
                {
                    SpeciesButton.SelectId(i);
                }
            }

            // If our species isn't available then reset it to default.
            if (Profile != null)
            {
                if (!speciesIds.Contains(Profile.Species))
                {
                    SetSpecies(SharedHumanoidAppearanceSystem.DefaultSpecies);
                }
            }
        }

        public void RefreshAntags()
        {
            AntagList.DisposeAllChildren();
            var items = new[]
            {
                ("humanoid-profile-editor-antag-preference-yes-button", 0),
                ("humanoid-profile-editor-antag-preference-no-button", 1)
            };

            foreach (var antag in _prototypeManager.EnumeratePrototypes<AntagPrototype>().OrderBy(a => Loc.GetString(a.Name)))
            {
                if (!antag.SetPreference)
                    continue;

                var antagContainer = new BoxContainer()
                {
                    Orientation = LayoutOrientation.Horizontal,
                };

                var selector = new RequirementsSelector()
                {
                    Margin = new Thickness(3f, 3f, 3f, 0f),
                };
                selector.OnOpenGuidebook += OnOpenGuidebook;

                var title = Loc.GetString(antag.Name);
                var description = Loc.GetString(antag.Objective);
                selector.Setup(items, title, 250, description, guides: antag.Guides);
                selector.Select(Profile?.AntagPreferences.Contains(antag.ID) == true ? 0 : 1);

                var requirements = _entManager.System<SharedRoleSystem>().GetAntagRequirement(antag);
                if (!_requirements.CheckRoleRequirements(requirements, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
                {
                    selector.LockRequirements(reason);
                    Profile = Profile?.WithAntagPreference(antag.ID, false);
                    SetDirty();
                }
                else
                {
                    selector.UnlockRequirements();
                }

                selector.OnSelected += preference =>
                {
                    Profile = Profile?.WithAntagPreference(antag.ID, preference == 0);
                    SetDirty();
                };

                antagContainer.AddChild(selector);

                antagContainer.AddChild(new Button()
                {
                    Disabled = true,
                    Text = Loc.GetString("loadout-window"),
                    HorizontalAlignment = HAlignment.Right,
                    Margin = new Thickness(3f, 0f, 0f, 0f),
                });

                AntagList.AddChild(antagContainer);
            }
        }

        private void SetDirty()
        {
            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Refresh all loadouts.
        /// </summary>
        public void RefreshLoadouts()
        {
            _loadoutWindow?.Dispose();
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            _entManager.DeleteEntity(PreviewDummy);
            PreviewDummy = EntityUid.Invalid;

            if (Profile == null || !_prototypeManager.HasIndex(Profile.Species))
                return;

            PreviewDummy = _controller.LoadProfileEntity(Profile, JobOverride, ShowClothes.Pressed);
            SpriteView.SetEntity(PreviewDummy);
            _entManager.System<MetaDataSystem>().SetEntityName(PreviewDummy, Profile.Name);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?) _preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateHairPickers();
            UpdateCMarkingsHair();
            UpdateCMarkingsFacialHair();

            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            RefreshOE14Stats();
            ReloadPreview();

            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int) Profile.PreferenceUnavailable);
            }
        }


        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null || !_entManager.EntityExists(PreviewDummy))
                return;

            _entManager.System<HumanoidAppearanceSystem>().LoadProfile(PreviewDummy, Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        private void OnSpeciesInfoButtonPressed(BaseButton.ButtonEventArgs args)
        {
            // TODO GUIDEBOOK
            // make the species guide book a field on the species prototype.
            // I.e., do what jobs/antags do.

            var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
            var species = Profile?.Species ?? SharedHumanoidAppearanceSystem.DefaultSpecies;
            var page = DefaultSpeciesGuidebook;
            if (_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                page = new ProtoId<GuideEntryPrototype>(species.Id); // Gross. See above todo comment.

            if (_prototypeManager.Resolve(DefaultSpeciesGuidebook, out var guideRoot))
            {
                var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>();
                dict.Add(DefaultSpeciesGuidebook, guideRoot);
                //TODO: Don't close the guidebook if its already open, just go to the correct page
                guidebookController.OpenGuidebook(dict, includeChildren:true, selected: page);
            }
        }

        /// <summary>
        /// Refreshes all job selectors.
        /// </summary>
        public void RefreshJobs()
        {
            JobList.DisposeAllChildren();
            _jobCategories.Clear();
            _jobPriorities.Clear();
            var firstCategory = true;

            // Get all displayed departments
            var departments = new List<DepartmentPrototype>();
            foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
            {
                if (department.EditorHidden)
                    continue;

                departments.Add(department);
            }

            departments.Sort(DepartmentUIComparer.Instance);

            var items = new[]
            {
                ("humanoid-profile-editor-job-priority-never-button", (int) JobPriority.Never),
                ("humanoid-profile-editor-job-priority-low-button", (int) JobPriority.Low),
                ("humanoid-profile-editor-job-priority-medium-button", (int) JobPriority.Medium),
                ("humanoid-profile-editor-job-priority-high-button", (int) JobPriority.High),
            };

            foreach (var department in departments)
            {
                var departmentName = Loc.GetString(department.Name);

                if (!_jobCategories.TryGetValue(department.ID, out var category))
                {
                    category = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                        Name = department.ID,
                        ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                            ("departmentName", departmentName))
                    };

                    if (firstCategory)
                    {
                        firstCategory = false;
                    }
                    else
                    {
                        category.AddChild(new Control
                        {
                            MinSize = new Vector2(0, 23),
                        });
                    }

                    category.AddChild(new PanelContainer
                    {
                        PanelOverride = new StyleBoxFlat {BackgroundColor = Color.FromHex("#464966")},
                        Children =
                        {
                            new Label
                            {
                                Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                    ("departmentName", departmentName)),
                                Margin = new Thickness(5f, 0, 0, 0)
                            }
                        }
                    });

                    _jobCategories[department.ID] = category;
                    JobList.AddChild(category);
                }

                var jobs = department.Roles.Select(jobId => _prototypeManager.Index(jobId))
                    .Where(job => job.SetPreference)
                    .ToArray();

                Array.Sort(jobs, JobUIComparer.Instance);

                foreach (var job in jobs)
                {
                    var jobContainer = new BoxContainer()
                    {
                        Orientation = LayoutOrientation.Horizontal,
                    };

                    var selector = new RequirementsSelector()
                    {
                        Margin = new Thickness(3f, 3f, 3f, 0f),
                    };
                    selector.OnOpenGuidebook += OnOpenGuidebook;

                    var icon = new TextureRect
                    {
                        TextureScale = new Vector2(2, 2),
                        VerticalAlignment = VAlignment.Center
                    };
                    var jobIcon = _prototypeManager.Index(job.Icon);
                    icon.Texture = _sprite.Frame0(jobIcon.Icon);
                    selector.Setup(items, job.LocalizedName, 200, job.LocalizedDescription, icon, job.Guides);

                    if (!_requirements.IsAllowed(job, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
                    {
                        selector.LockRequirements(reason);
                    }
                    else
                    {
                        selector.UnlockRequirements();
                    }

                    selector.OnSelected += selectedPrio =>
                    {
                        var selectedJobPrio = (JobPriority) selectedPrio;
                        Profile = Profile?.WithJobPriority(job.ID, selectedJobPrio);

                        foreach (var (jobId, other) in _jobPriorities)
                        {
                            // Sync other selectors with the same job in case of multiple department jobs
                            if (jobId == job.ID)
                            {
                                other.Select(selectedPrio);
                                continue;
                            }

                            if (selectedJobPrio != JobPriority.High || (JobPriority) other.Selected != JobPriority.High)
                                continue;

                            // Lower any other high priorities to medium.
                            other.Select((int)JobPriority.Medium);
                            Profile = Profile?.WithJobPriority(jobId, JobPriority.Medium);
                        }

                        // TODO: Only reload on high change (either to or from).
                        ReloadPreview();

                        UpdateJobPriorities();
                        SetDirty();
                    };

                    var loadoutWindowBtn = new Button()
                    {
                        Text = Loc.GetString("loadout-window"),
                        HorizontalAlignment = HAlignment.Right,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(3f, 3f, 0f, 0f),
                    };

                    var collection = IoCManager.Instance!;
                    var protoManager = collection.Resolve<IPrototypeManager>();

                    // If no loadout found then disabled button
                    if (!protoManager.TryIndex<RoleLoadoutPrototype>(LoadoutSystem.GetJobPrototype(job.ID), out var roleLoadoutProto))
                    {
                        loadoutWindowBtn.Disabled = true;
                    }
                    // else
                    else
                    {
                        loadoutWindowBtn.OnPressed += args =>
                        {
                            RoleLoadout? loadout = null;

                            // Clone so we don't modify the underlying loadout.
                            Profile?.Loadouts.TryGetValue(LoadoutSystem.GetJobPrototype(job.ID), out loadout);
                            loadout = loadout?.Clone();

                            if (loadout == null)
                            {
                                loadout = new RoleLoadout(roleLoadoutProto.ID);
                                loadout.SetDefault(Profile, _playerManager.LocalSession, _prototypeManager);
                            }

                            OpenLoadout(job, loadout, roleLoadoutProto);
                        };
                    }

                    _jobPriorities.Add((job.ID, selector));
                    jobContainer.AddChild(selector);
                    jobContainer.AddChild(loadoutWindowBtn);
                    category.AddChild(jobContainer);
                }
            }

            UpdateJobPriorities();
        }

        private void OpenLoadout(JobPrototype? jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto)
        {
            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
            var collection = IoCManager.Instance;

            if (collection == null || _playerManager.LocalSession == null || Profile == null)
                return;

            JobOverride = jobProto;
            var session = _playerManager.LocalSession;

            _loadoutWindow = new LoadoutWindow(Profile, roleLoadout, roleLoadoutProto, _playerManager.LocalSession, collection)
            {
                Title = Loc.GetString("loadout-window-title-loadout", ("job", $"{jobProto?.LocalizedName}")),
            };

            // Refresh the buttons etc.
            _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
            _loadoutWindow.OpenCenteredLeft();

            _loadoutWindow.OnNameChanged += name =>
            {
                roleLoadout.EntityName = name;
                Profile = Profile.WithLoadout(roleLoadout);
                SetDirty();
            };

            _loadoutWindow.OnLoadoutPressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.AddLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            _loadoutWindow.OnLoadoutUnpressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.RemoveLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            JobOverride = jobProto;
            ReloadPreview();

            _loadoutWindow.OnClose += () =>
            {
                JobOverride = null;
                ReloadPreview();
            };

            if (Profile is null)
                return;

            UpdateJobPriorities();
        }

        private void OnFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithFlavorText(content);
            SetDirty();
        }

        private void OnMarkingChange(MarkingSet markings)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(markings.GetForwardEnumerator().ToList()));
            ReloadProfilePreview();
        }

        private void OnSkinColorOnValueChanged()
        {
            if (Profile is null) return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                {
                    if (!Skin.Visible)
                    {
                        Skin.Visible = true;
                        RgbSkinColorContainer.Visible = false;
                    }

                    var color = strategy.FromUnary(Skin.Value);

                    Markings.CurrentSkinColor = color;
                    Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

                    break;
                }
                case SkinColorationStrategyInput.Color:
                {
                    if (!RgbSkinColorContainer.Visible)
                    {
                        Skin.Visible = false;
                        RgbSkinColorContainer.Visible = true;
                    }

                    var color = strategy.ClosestSkinColor(_rgbSkinColorSelector.Color);

                    Markings.CurrentSkinColor = color;
                    Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

                    break;
                }
            }

            ReloadProfilePreview();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            _entManager.DeleteEntity(PreviewDummy);
            PreviewDummy = EntityUid.Invalid;
        }

        private void SetAge(int newAge)
        {
            Profile = Profile?.WithAge(newAge);
            ReloadPreview();
        }

        private void SetSex(Sex newSex)
        {
            Profile = Profile?.WithSex(newSex);
            // for convenience, default to most common gender when new sex is selected
            switch (newSex)
            {
                case Sex.Male:
                    Profile = Profile?.WithGender(Gender.Male);
                    break;
                case Sex.Female:
                    Profile = Profile?.WithGender(Gender.Female);
                    break;
                default:
                    Profile = Profile?.WithGender(Gender.Epicene);
                    break;
            }

            UpdateGenderControls();
            Markings.SetSex(newSex);
            ReloadPreview();
        }

        private void SetGender(Gender newGender)
        {
            Profile = Profile?.WithGender(newGender);
            ReloadPreview();
        }

        private void SetSpecies(string newSpecies)
        {
            Profile = Profile?.WithSpecies(newSpecies);
            OnSkinColorOnValueChanged(); // Species may have special color prefs, make sure to update it.
            Markings.SetSpecies(newSpecies); // Repopulate the markings tab as well.
            // In case there's job restrictions for the species
            RefreshJobs();
            // In case there's species restrictions for loadouts
            RefreshLoadouts();
            UpdateSexControls(); // update sex for new species
            UpdateSpeciesGuidebookIcon();
            ReloadPreview();
        }

        private void SetName(string newName)
        {
            Profile = Profile?.WithName(newName);
            SetDirty();

            if (!IsDirty)
                return;

            _entManager.System<MetaDataSystem>().SetEntityName(PreviewDummy, newName);
        }

        private void SetSpawnPriority(SpawnPriorityPreference newSpawnPriority)
        {
            Profile = Profile?.WithSpawnPriorityPreference(newSpawnPriority);
            SetDirty();
        }

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private void UpdateNameEdit()
        {
            NameEdit.Text = Profile?.Name ?? "";
        }

        private void UpdateFlavorTextEdit()
        {
            if (_flavorTextEdit != null)
            {
                _flavorTextEdit.TextRope = new Rope.Leaf(Profile?.FlavorText ?? "");
            }
        }

        private void UpdateAgeEdit()
        {
            AgeEdit.Text = Profile?.Age.ToString() ?? "";
        }

        /// <summary>
        /// Updates selected job priorities to the profile's.
        /// </summary>
        private void UpdateJobPriorities()
        {
            foreach (var (jobId, prioritySelector) in _jobPriorities)
            {
                var priority = Profile?.JobPriorities.GetValueOrDefault(jobId, JobPriority.Never) ?? JobPriority.Never;
                prioritySelector.Select((int) priority);
            }
        }

        private void UpdateSexControls()
        {
            if (Profile == null)
                return;

            SexButton.Clear();

            var sexes = new List<Sex>();

            // add species sex options, default to just none if we are in bizzaro world and have no species
            if (_prototypeManager.Resolve<SpeciesPrototype>(Profile.Species, out var speciesProto))
            {
                foreach (var sex in speciesProto.Sexes)
                {
                    sexes.Add(sex);
                }
            }
            else
            {
                sexes.Add(Sex.Unsexed);
            }

            // add button for each sex
            foreach (var sex in sexes)
            {
                SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int) sex);
            }

            if (sexes.Contains(Profile.Sex))
                SexButton.SelectId((int) Profile.Sex);
            else
                SexButton.SelectId((int) sexes[0]);
        }

        private void UpdateSkinColor()
        {
            if (Profile == null)
                return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                {
                    if (!Skin.Visible)
                    {
                        Skin.Visible = true;
                        RgbSkinColorContainer.Visible = false;
                    }

                    Skin.Value = strategy.ToUnary(Profile.Appearance.SkinColor);

                    break;
                }
                case SkinColorationStrategyInput.Color:
                {
                    if (!RgbSkinColorContainer.Visible)
                    {
                        Skin.Visible = false;
                        RgbSkinColorContainer.Visible = true;
                    }

                    _rgbSkinColorSelector.Color = strategy.ClosestSkinColor(Profile.Appearance.SkinColor);

                    break;
                }
            }
        }

        public void UpdateSpeciesGuidebookIcon()
        {
            SpeciesInfoButton.StyleClasses.Clear();

            var species = Profile?.Species;
            if (species is null)
                return;

            if (!_prototypeManager.Resolve<SpeciesPrototype>(species, out var speciesProto))
                return;

            // Don't display the info button if no guide entry is found
            if (!_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                return;

            const string style = "SpeciesInfoDefault";
            SpeciesInfoButton.StyleClasses.Add(style);
        }

        private void UpdateMarkings()
        {
            if (Profile == null)
            {
                return;
            }

            Markings.SetData(Profile.Appearance.Markings, Profile.Species,
                Profile.Sex, Profile.Appearance.SkinColor, Profile.Appearance.EyeColor
            );
        }

        private void UpdateGenderControls()
        {
            if (Profile == null)
            {
                return;
            }

            PronounsButton.SelectId((int) Profile.Gender);
        }

        private void UpdateSpawnPriorityControls()
        {
            if (Profile == null)
            {
                return;
            }

            SpawnPriorityButton.SelectId((int) Profile.SpawnPriority);
        }

        private void UpdateHairPickers()
        {
            if (Profile == null)
            {
                return;
            }
            var hairMarking = Profile.Appearance.HairStyleId == HairStyles.DefaultHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.HairStyleId, new List<Color>() { Profile.Appearance.HairColor }) };

            var facialHairMarking = Profile.Appearance.FacialHairStyleId == HairStyles.DefaultFacialHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.FacialHairStyleId, new List<Color>() { Profile.Appearance.FacialHairColor }) };

            HairStylePicker.UpdateData(
                hairMarking,
                Profile.Species,
                1);
            FacialHairPicker.UpdateData(
                facialHairMarking,
                Profile.Species,
                1);
        }

        private void UpdateCMarkingsHair()
        {
            if (Profile == null)
            {
                return;
            }

            // hair color
            Color? hairColor = null;
            if ( Profile.Appearance.HairStyleId != HairStyles.DefaultHairStyle &&
                _markingManager.Markings.TryGetValue(Profile.Appearance.HairStyleId, out var hairProto)
            )
            {
                if (_markingManager.CanBeApplied(Profile.Species, Profile.Sex, hairProto, _prototypeManager))
                {
                    if (_markingManager.MustMatchSkin(Profile.Species, HumanoidVisualLayers.Hair, out var _, _prototypeManager))
                    {
                        hairColor = Profile.Appearance.SkinColor;
                    }
                    else
                    {
                        hairColor = Profile.Appearance.HairColor;
                    }
                }
            }
            if (hairColor != null)
            {
                Markings.HairMarking = new (Profile.Appearance.HairStyleId, new List<Color>() { hairColor.Value });
            }
            else
            {
                Markings.HairMarking = null;
            }
        }

        private void UpdateCMarkingsFacialHair()
        {
            if (Profile == null)
            {
                return;
            }

            // facial hair color
            Color? facialHairColor = null;
            if ( Profile.Appearance.FacialHairStyleId != HairStyles.DefaultFacialHairStyle &&
                _markingManager.Markings.TryGetValue(Profile.Appearance.FacialHairStyleId, out var facialHairProto))
            {
                if (_markingManager.CanBeApplied(Profile.Species, Profile.Sex, facialHairProto, _prototypeManager))
                {
                    if (_markingManager.MustMatchSkin(Profile.Species, HumanoidVisualLayers.Hair, out var _, _prototypeManager))
                    {
                        facialHairColor = Profile.Appearance.SkinColor;
                    }
                    else
                    {
                        facialHairColor = Profile.Appearance.FacialHairColor;
                    }
                }
            }
            if (facialHairColor != null)
            {
                Markings.FacialHairMarking = new (Profile.Appearance.FacialHairStyleId, new List<Color>() { facialHairColor.Value });
            }
            else
            {
                Markings.FacialHairMarking = null;
            }
        }

        private void UpdateEyePickers()
        {
            if (Profile == null)
            {
                return;
            }

            Markings.CurrentEyeColor = Profile.Appearance.EyeColor;
            EyeColorPicker.SetData(Profile.Appearance.EyeColor);
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction) ((int) direction % 4 * 2);
        }

        private void RandomizeEverything()
        {
            Profile = HumanoidCharacterProfile.Random();
            SetProfile(Profile, CharacterSlot);
            SetDirty();
        }

        private void RandomizeName()
        {
            if (Profile == null) return;
            var name = HumanoidCharacterProfile.GetName(Profile.Species, Profile.Gender);
            SetName(name);
            UpdateNameEdit();
        }

        private async void ExportImage()
        {
            if (_imaging)
                return;

            var dir = SpriteView.OverrideDirection ?? Direction.South;

            // I tried disabling the button but it looks sorta goofy as it only takes a frame or two to save
            _imaging = true;
            await _entManager.System<ContentSpriteSystem>().Export(PreviewDummy, dir, includeId: false);
            _imaging = false;
        }

        private async void ImportProfile()
        {
            if (_exporting || CharacterSlot == null || Profile == null)
                return;

            StartExport();
            await using var file = await _dialogManager.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var profile = _entManager.System<HumanoidAppearanceSystem>().FromStream(file, _playerManager.LocalSession!);
                var oldProfile = Profile;
                SetProfile(profile, CharacterSlot);

                IsDirty = !profile.MemberwiseEquals(oldProfile);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when importing profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
            }
        }

        private async void ExportProfile()
        {
            if (Profile == null || _exporting)
                return;

            StartExport();
            var file = await _dialogManager.SaveFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var dataNode = _entManager.System<HumanoidAppearanceSystem>().ToDataNode(Profile);
                await using var writer = new StreamWriter(file.Value.fileStream);
                dataNode.Write(writer);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when exporting profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
                await file.Value.fileStream.DisposeAsync();
            }
        }

        private void StartExport()
        {
            _exporting = true;
            ImportButton.Disabled = true;
            ExportButton.Disabled = true;
        }

        private void EndExport()
        {
            _exporting = false;
            ImportButton.Disabled = false;
            ExportButton.Disabled = false;
        }

        /// <summary>
        /// Calculates the total stat bonus from free learned skills (spells) for a given stat.
        /// Returns 0 if no spells grant bonus to that stat.
        /// </summary>
        private int OE14GetSpellBonusForStat(string statName)
        {
            if (Profile == null)
                return 0;

            // Get the species prototype to find free learned skills
            if (!_prototypeManager.TryIndex<SpeciesPrototype>(Profile.Species, out var specProto))
                return 0;

            if (!_prototypeManager.TryIndex<EntityPrototype>(specProto.Prototype, out var entProto))
                return 0;

            // Look for OE14SkillStorage component which lists free skills
            if (!entProto.TryGetComponent<Content.Shared._OE14.Skill.Components.OE14SkillStorageComponent>(
                out var skillStorageComp, _entManager.ComponentFactory))
                return 0;

            if (skillStorageComp == null || skillStorageComp.FreeLearnedSkills == null)
                return 0;

            var freeSkillsList = skillStorageComp.FreeLearnedSkills;

            int totalBonus = 0;

            // For each free skill, check if it has OE14AddStatBonus effect for our stat
            foreach (var skillId in freeSkillsList)
            {
                if (!_prototypeManager.TryIndex(skillId, out OE14SkillPrototype? skillProto))
                    continue;

                if (skillProto == null)
                    continue;

                // Check effects for OE14AddStatBonus
                if (skillProto.Effects != null)
                {
                    foreach (var effect in skillProto.Effects)
                    {
                        if (effect is Content.Shared._OE14.Skill.Effects.OE14AddStatBonus statBonus &&
                            statBonus.Stat.Equals(statName, StringComparison.OrdinalIgnoreCase))
                        {
                            totalBonus += 1; // Each T1/T2 gives +1
                        }
                    }
                }
            }

            return totalBonus;
        }

        /// <summary>
        /// Creates a two-layer bar inside <paramref name="slot"/>:
        /// - Background: very dark version of the stat color
        /// - Foreground: full stat color, width tracks value/10
        /// Returns a setter callback to update the fill ratio (0-1).
        /// </summary>
        private static void OE14BuildStatBar(BoxContainer slot, Color color, out Action<float> setter)
        {
            var dark = new Color(color.R * 0.18f, color.G * 0.18f, color.B * 0.18f);

            var layout = new LayoutContainer { HorizontalExpand = true, MinHeight = 10 };

            var bg = new PanelContainer { PanelOverride = new StyleBoxFlat { BackgroundColor = dark } };
            LayoutContainer.SetAnchorRight(bg, 1f);
            LayoutContainer.SetAnchorBottom(bg, 1f);
            layout.AddChild(bg);

            var fg = new PanelContainer { PanelOverride = new StyleBoxFlat { BackgroundColor = color } };
            LayoutContainer.SetAnchorRight(fg, 0f);
            LayoutContainer.SetAnchorBottom(fg, 1f);
            layout.AddChild(fg);

            slot.AddChild(layout);

            setter = ratio =>
            {
                ratio = Math.Clamp(ratio, 0f, 1f);
                LayoutContainer.SetAnchorRight(fg, ratio);
            };
        }

        /// <summary>
        /// Populates a BoxContainer with modifier labels.
        /// Shows both "Spend" and "Spell" modifiers.
        /// </summary>
        private static void OE14PopulateModifierContainer(BoxContainer container, int spendBonus, int spellBonus)
        {
            container.RemoveAllChildren();

            bool first = true;

            if (spellBonus != 0)
            {
                if (!first)
                {
                    var separator = new Label { Text = ", ", FontColorOverride = Color.FromHex("#999999") };
                    container.AddChild(separator);
                }

                var sign = spellBonus > 0 ? "+" : "";
                var label = new Label
                {
                    Text = $"{sign}{spellBonus} SPEL",
                    FontColorOverride = Color.FromHex("#d946ef")
                };
                container.AddChild(label);
                first = false;
            }

            if (spendBonus != 0)
            {
                if (!first)
                {
                    var separator = new Label { Text = ", ", FontColorOverride = Color.FromHex("#999999") };
                    container.AddChild(separator);
                }

                var sign = spendBonus > 0 ? "+" : "";
                var label = new Label
                {
                    Text = $"{sign}{spendBonus} SPND",
                    FontColorOverride = Color.FromHex("#f0c050")
                };
                container.AddChild(label);
            }
        }
    }
}
