using Content.Shared._OE14.CommunicationCrystal;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._OE14.CommunicationCrystal;

[GenerateTypedNameReferences]
public sealed partial class OE14CommunicationCrystalWindow : Robust.Client.UserInterface.CustomControls.DefaultWindow
{
    public event Action<bool, string>? OnSendMessage;
    public event Action? OnRemoveCrystal;
    private const int MaxChars = 500;

    public OE14CommunicationCrystalWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GlobalButton.OnPressed += OnGlobalPressed;
        LocalButton.OnPressed += OnLocalPressed;
        RemoveButton.OnPressed += OnRemovePressed;
        MessageTextBox.OnTextChanged += _ =>
        {
            var text = GetMessageText();
            var length = text.Length;

            CharCountLabel.Text = $"{length} / {MaxChars}";

            if (length > MaxChars)
            {
                CharCountLabel.Modulate = Color.Red;
            }
            else if (length > 450)
            {
                CharCountLabel.Modulate = Color.Yellow;
            }
            else
            {
                CharCountLabel.Modulate = Color.White;
            }
        };
    }

    private void OnGlobalPressed(BaseButton.ButtonEventArgs args)
    {
        var message = GetMessageText();

        if (string.IsNullOrWhiteSpace(message))
            return;

        if (message.Length > 500)
            return;

        OnSendMessage?.Invoke(true, message);
    }

    private void OnLocalPressed(BaseButton.ButtonEventArgs args)
    {
        var message = GetMessageText();

        if (string.IsNullOrWhiteSpace(message))
            return;

        if (message.Length > 500)
            return;

        OnSendMessage?.Invoke(false, message);
    }

    private void OnRemovePressed(BaseButton.ButtonEventArgs args)
    {
        OnRemoveCrystal?.Invoke();
    }

    private string GetMessageText()
    {
        if (MessageTextBox.TextRope == null)
            return string.Empty;

        return Rope.Collapse(MessageTextBox.TextRope);
    }

    public void UpdateState(OE14CommunicationCrystalUiState state)
    {
        EnergyValueLabel.Text = $"{state.CurrentEnergy}/{state.MaxEnergy}";
        CrystalStatusValueLabel.Text = state.HasEnergyCrystal ? Loc.GetString("oe14-comm-crystal-inserted") : Loc.GetString("oe14-comm-crystal-not-inserted");

        GlobalButton.Disabled = !state.CanSendGlobal;
        LocalButton.Disabled = !state.HasEnergyCrystal;
        RemoveButton.Disabled = !state.HasEnergyCrystal;

        if (state.GlobalCooldown.HasValue)
        {
            CooldownLabel.Text = $"{Loc.GetString("oe14-comm-crystal-global-cooldown")} {(int) state.GlobalCooldown.Value.TotalSeconds}s";
            GlobalButton.Disabled = true;
        }
        else
        {
            CooldownLabel.Text = "";
        }
    }
}