/*
 * This file is sublicensed under MIT License
 * https://github.com/space-wizards/space-station-14/blob/master/LICENSE.TXT
 */

using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._OE14.Cooking.Prototypes;
using Content.Shared._OE14.Cooking.Requirements;
using Content.Shared.Chemistry.Reagent;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

/// <summary>
///     Control for embedding a cooking recipe card into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideCookingRecipeEmbed : BoxContainer, IDocumentTag, ISearchableControl, IPrototypeRepresentationControl
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly ISawmill _sawmill;

    public IPrototype? RepresentedPrototype { get; private set; }

    public GuideCookingRecipeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.cooking_recipe");
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideCookingRecipeEmbed(OE14CookingRecipePrototype recipe) : this()
    {
        GenerateControl(recipe);
    }

    public bool CheckMatchesSearch(string query) => this.ChildrenContainText(query);

    public void SetHiddenState(bool state, string query) =>
        Visible = CheckMatchesSearch(query) ? state : !state;

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Recipe", out var id))
        {
            _sawmill.Error("Cooking recipe embed tag is missing Recipe argument");
            return false;
        }

        if (!_prototype.TryIndex<OE14CookingRecipePrototype>(id, out var recipe))
        {
            _sawmill.Error($"Specified cooking recipe prototype \"{id}\" is not valid");
            return false;
        }

        GenerateControl(recipe);
        control = this;
        return true;
    }

    private void GenerateControl(OE14CookingRecipePrototype recipe)
    {
        RepresentedPrototype = recipe;

        // Recipe name
        var name = recipe.FoodData.Name is not null
            ? Loc.GetString(recipe.FoodData.Name)
            : recipe.ID;
        RecipeName.SetMarkup(name);

        // Ingredient + result icons
        GenerateIcons(recipe);

        // Requirements
        var reqLines = new List<string>();
        foreach (var req in recipe.Requirements)
        {
            switch (req)
            {
                case TagRequired tagReq:
                {
                    var tagNames = tagReq.Tags.Select(t => FormatTagName(t.ToString()));
                    var orWord = " " + Loc.GetString("oe14-guidebook-cooking-or") + " ";
                    reqLines.Add("• " + string.Join(orWord, tagNames));
                    break;
                }
                case ReagentRequired reagentReq:
                {
                    var names = reagentReq.Reagents.Select(r =>
                        _prototype.TryIndex<ReagentPrototype>(r, out var rp) ? rp.LocalizedName : r.ToString());
                    reqLines.Add($"• {reagentReq.Amount}u " + string.Join(", ", names));
                    break;
                }
                case TagBlocked tagBlocked:
                {
                    var tagNames = tagBlocked.Tags.Select(t => FormatTagName(t.ToString()));
                    var blockedLabel = Loc.GetString("oe14-guidebook-cooking-blocked");
                    reqLines.Add("[color=#ff6666]• " + blockedLabel + " " + string.Join(", ", tagNames) + "[/color]");
                    break;
                }
            }
        }

        if (reqLines.Count > 0)
        {
            RequirementsLabel.SetMarkup(string.Join("\n", reqLines));
        }
        else
        {
            RequirementsContainer.Visible = false;
        }

        // Description
        if (recipe.FoodData.Desc is not null)
        {
            RecipeDescription.SetMarkup(Loc.GetString(recipe.FoodData.Desc));
        }
        else
        {
            RecipeDescription.Visible = false;
        }
    }

    /// <summary>
    ///     Maps known cooking tag IDs to a representative entity prototype ID for display.
    /// </summary>
    private static readonly Dictionary<string, string> TagToEntity = new()
    {
        { "OE14Meat",        "OE14FoodMeatLamb" },
        { "OE14MeatSlice",   "OE14FoodMeatLambSlice" },
        { "OE14MeatPig",     "OE14FoodMeatPig" },
        { "OE14MeatLeg",     "OE14FoodMeatPigLeg" },
        { "OE14MeatMonster", "OE14FoodMeatMonster" },
        { "OE14Salad",       "OE14FoodCabbage" },
        { "OE14Vegetable",   "OE14FoodCucumber" },
        { "OE14Potato",      "OE14FoodPotato" },
        { "OE14Cheese",      "OE14FoodCheesePart" },
        { "OE14Dough",       "OE14FoodDoughLarge" },
        { "OE14Egg",         "OE14FoodEgg" },
        { "OE14Pumpkin",     "OE14FoodPumpkin" },
    };

    private void GenerateIcons(OE14CookingRecipePrototype recipe)
    {
        // Ingredient icons: one representative entity per TagRequired, with label
        var addedTags = new HashSet<string>();
        foreach (var req in recipe.Requirements)
        {
            if (req is TagRequired tagReq)
            {
                foreach (var tag in tagReq.Tags)
                {
                    var tagStr = tag.ToString();
                    if (addedTags.Contains(tagStr) || !TagToEntity.TryGetValue(tagStr, out var entId))
                        continue;

                    addedTags.Add(tagStr);
                    IconsContainer.AddChild(MakeIngredientSlot(entId, FormatTagName(tagStr)));
                    break;
                }
            }
            else if (req is ReagentRequired reagentReq)
            {
                // Show reagent as text label (e.g. 20u Água)
                var names = reagentReq.Reagents.Select(r =>
                    _prototype.TryIndex<ReagentPrototype>(r, out var rp) ? rp.LocalizedName : r.ToString());
                var slot = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalAlignment = HAlignment.Center, Margin = new Thickness(2, 0) };
                slot.AddChild(new Label { Text = $"{reagentReq.Amount}u", HorizontalAlignment = HAlignment.Center, StyleClasses = { "LabelSmall" } });
                slot.AddChild(new Label { Text = string.Join(", ", names), HorizontalAlignment = HAlignment.Center, StyleClasses = { "LabelSmall" } });
                IconsContainer.AddChild(slot);
            }
        }

        if (IconsContainer.ChildCount == 0)
        {
            IconsContainer.Visible = false;
            return;
        }

        // Arrow separator
        IconsContainer.AddChild(new Label { Text = " → ", VerticalAlignment = VAlignment.Center });

        // Result entity
        string resultCaption;
        string resultEntity;
        if (recipe.FoodData.SliceProto.HasValue)
        {
            resultEntity = recipe.FoodData.SliceProto.Value.ToString();
            resultCaption = recipe.FoodData.Name is not null ? Loc.GetString(recipe.FoodData.Name) : recipe.ID;
        }
        else if (recipe.FoodType.ToString() == "Soup")
        {
            resultEntity = "OE14BowlWooden";
            resultCaption = recipe.FoodData.Name is not null ? Loc.GetString(recipe.FoodData.Name) : recipe.ID;
        }
        else
        {
            resultEntity = "OE14PlateWooden";
            resultCaption = recipe.FoodData.Name is not null ? Loc.GetString(recipe.FoodData.Name) : recipe.ID;
        }
        IconsContainer.AddChild(MakeIngredientSlot(resultEntity, resultCaption));
    }

    private static BoxContainer MakeIngredientSlot(string entId, string label)
    {
        var slot = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(2, 0),
        };
        slot.AddChild(new GuideEntityEmbed(entId, false, false));
        slot.AddChild(new Label
        {
            Text = label,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { "LabelSmall" },
        });
        return slot;
    }

    /// <summary>
    ///     Formats a tag prototype ID like "OE14MeatSlice" into "Meat Slice".
    /// </summary>
    private static string FormatTagName(string tagId)
    {
        var name = tagId.StartsWith("OE14") ? tagId[4..] : tagId;
        var sb = new StringBuilder();
        for (var i = 0; i < name.Length; i++)
        {
            if (i > 0 && char.IsUpper(name[i]))
                sb.Append(' ');
            sb.Append(name[i]);
        }
        return sb.ToString();
    }
}
