/*
 * This file is sublicensed under MIT License
 * https://github.com/space-wizards/space-station-14/blob/master/LICENSE.TXT
 */

using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client.Guidebook.Richtext;
using Content.Shared._OE14.Cooking.Prototypes;
using Content.Shared._OE14.Cooking.Requirements;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

/// <summary>
///     Control for embedding all cooking recipes of a given FoodType into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideCookingRecipeGroupEmbed : BoxContainer, IDocumentTag
{
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;

    public GuideCookingRecipeGroupEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.cooking_recipe_group");
        MouseFilter = MouseFilterMode.Stop;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("FoodType", out var foodType))
        {
            _sawmill.Error("Cooking recipe group embed tag is missing FoodType argument");
            return false;
        }

        // Skip "trash" recipes (those with AlwaysMet requirement — the fallback when no real recipe matches)
        var recipes = _prototype.EnumeratePrototypes<OE14CookingRecipePrototype>()
            .Where(p => p.FoodType.ToString() == foodType
                        && !p.Requirements.Any(r => r is AlwaysMet))
            .OrderBy(p => p.FoodData.Name is not null ? Loc.GetString(p.FoodData.Name) : p.ID);

        foreach (var recipe in recipes)
        {
            GroupContainer.AddChild(new GuideCookingRecipeEmbed(recipe));
        }

        control = this;
        return true;
    }
}
