using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._OE14.Options;

[GenerateTypedNameReferences]
public sealed partial class OE14OptionsMenuMainTab : Control
{
    public OE14OptionsMenuMainTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.WaveShaderEnabled, WaveShaderEnabled);
        Control.AddOptionCheckBox(CCVars.PostProcess, PostProcessCheckBox);

        Control.Initialize();
    }
}
